server:
  port: 6001

eureka:
  instance:
    hostname: localhost
  client: #not a client,don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 15000 # 清理间隔（单位毫秒，默认是60*1000）





