spring:
  application:
    name: zuul

server:
  port: 6601

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
#网关配置
zuul:
  routes:
    api-masterdata:
      path: /masterdata/**
      serviceId: masterdata
#熔断保护
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000